# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='deviceType',
            field=models.CharField(default='device', max_length=25),
        ),
        migrations.AlterField(
            model_name='work',
            name='serialNumber',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
